# Notes

Exam contains 6 problems, Most of them are of intermediate complexity and follow the material from class or graded assignments. Note, that no loops are allowed in this exam, and all the solutions containing loops will be graded as 0.

For this exam you'll need [Titanic](https://www.kaggle.com/c/titanic) and [road accidents](https://www.kaggle.com/daveianhickey/2000-16-traffic-flow-england-scotland-wales) datasets.

In [3]:
%pylab inline
plt.style.use("bmh")

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [4]:
plt.rcParams["figure.figsize"] = (6,6)

In [5]:
import numpy as np
import pandas as pd
import torch

In [6]:
STUDENT = "Amir Alikulov"
ASSIGNMENT = "exam"
TEST = False

In [7]:
if TEST:
    import solutions
    total_grade = 0
    MAX_POINTS = 10

# NumPy

### 1. Filtering array (2 points).

Clip array values according to the following:

- given a two-dimensional array `arr` and threshold value `max_val`,
- find those rows, for which row values sum is `> max_val`,
- and replace largest value for each of those rows with `v` $\rightarrow$ `v - <row sum> + max_val`.

For example, consider the following array and threshold `max_val=8`:

In [8]:
a = np.array([[1, 5, 4], [-3, 2, 8]])

# largest_sum_row_index = np.argmax(a.sum(axis=1))

a_copy = a.copy()
row_sum = a_copy.sum(axis=1)
row_mask = row_sum > 1
print(row_mask)
a_copy[row_mask]
np.argmax(a_copy[row_sum > 1], axis=1)




[ True  True]


array([1, 2])

Row sums are:

In [9]:
a.sum(axis=1)

array([10,  7])

Since row sum for row `0` is `> max_val`, largest value in that row (`a[0, 1]`, which is `5`), must be replaced with: `5 - 10 + 8 = 3`, resulting in:

In [10]:
a_clipped = np.array([[1, 3, 4], [-3, 2, 8]])
a_clipped

array([[ 1,  3,  4],
       [-3,  2,  8]])

#### Notes:

- **do not change original array**,
- in this problem you may need to use **boolean and fancy indexing**, as well as `arr.argmax(...)`,
- you **cannot use loops**,
- input array is of **any two-dimensional shape** (including `(N,1)` and `(1,N)`), filled with **random integers**,
- there may be no rows, which satisfy threshold condition, and in that case resulting array must be identical to input array.

In [11]:
def clip_array(arr, max_val):
    """Clip array based on `max_val`."""

    arr_copy = arr.copy()
    row_sums = arr.sum(axis=1)
    rows_to_modify = row_sums > max_val
    max_indices = arr.argmax(axis=1)
    arr_copy[rows_to_modify, max_indices[rows_to_modify]] = arr[rows_to_modify, max_indices[rows_to_modify]] - row_sums[rows_to_modify] + max_val

    return arr_copy

clip_array(a, 8)

array([[ 1,  3,  4],
       [-3,  2,  8]])

In [12]:
PROBLEM_ID = 1

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, clip_array)

### 2. Calculate area (1 point).

In this problem you will construct a naive Monte-Carlo simulator. Provided with a 2D bounding box, you must calculate it's area:

- a bounding box is specified by maximum and minimum `x` and `y`, i.e. a bounding box is a **rectangle** between `minx` and `maxx` over `x`-axis and between `miny` and `maxy` over `y`-axis,
- all of `minx`, `maxx`, `miny`, `maxy` are `>=0` and `<=1`,
- you can sample **at most** `n_samples` points on 2D place,
- ratio of number of points inside a bounding box to total number of points is an **estimate of bounding box area**,
- estimate is considered valid, if it's **no more than 10% off of actual area value**,
- `n_samples` is chosen in such a way, that **10% error is achievable nearly always**, i.e. chances of getting more then 10% error with correct computation are negligibly small.

For example, a bounding box is `minx=0.25`, `maxx=0.5`, `miny=0.1`, `maxy=0.6`. Actual area is `0.125`. Suppose, that we sample `10000` points in unit square $x \in [0, 1],\,y \in [0, 1]$ and 1215 of them are inside the bounding box. Then, an estimate for the bounding box area is `0.1215` (with error of about 2.8%). Image below illustrates this example.

![Monte-Carlo integration example](mc.png)

In [ ]:
def calc_area(minx, maxx, miny, maxy, n_samples):
    """Calculate area of bounding box."""

    pass

In [ ]:
PROBLEM_ID = 2

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, calc_area)

### 3. Find outliers (3 points).

Given an array of shape `(N,2)`, filter all the rows, which are more than `thr` away from other rows. Distance metrics is Euclidean, i.e. distance between rows `i` and `j` is (in pseudocode):

```
distance(i, j) = sqrt(square(arr[i, 0] - arr[j, 0]) + square(arr[i, 1] - arr[j, 1]))
```

Distance of row `i` from other rows is:

```
distance(i) = mean(distance(i, j)), j!=i
```

Rows, which have `distance(i) > thr` must be filtered. In this problem you **cannot use loops**. Instead, use broadcasting (recall recurrence matrix problem in GA-2 and extend it to two-dimensional case).

As an example, consider 1000 samples from standard normal distribution for `x` (axis 1) and `y` (axis 0) and threshold of 2:

![Outliers filtering](outliers.png)

In [47]:
#arr. thr

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])

a = arr[:, np.newaxis, :]  # Shape: (N,1,2)
b = arr[np.newaxis, :, :]  # Shape: (1,N,2)

# Calculate squared differences for all pairs of points
# This gives us an (N,N,2) array of differences
diff = a - b


distances = np.sqrt(np.sum(diff**2, axis=2))
mean_distances = np.sum(distances, axis=1) / (len(arr) - 1)





array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ,
        14.14213562, 16.97056275, 19.79898987, 22.627417  , 25.45584412],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        11.3137085 , 14.14213562, 16.97056275, 19.79898987, 22.627417  ],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425,
         8.48528137, 11.3137085 , 14.14213562, 16.97056275, 19.79898987],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712,
         5.65685425,  8.48528137, 11.3137085 , 14.14213562, 16.97056275],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ,
         2.82842712,  5.65685425,  8.48528137, 11.3137085 , 14.14213562],
       [14.14213562, 11.3137085 ,  8.48528137,  5.65685425,  2.82842712,
         0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [16.97056275, 14.14213562, 11.3137085 ,  8.48528137,  5.65685425,
         2.82842712,  0.        ,  2.82842712

In [51]:
np.mean([2.828427,5.656854,8.485281,11.313708,14.142136,16.970563,19.798990,22.627417,25.455844])

14.142135555555555

In [52]:
mean_distances = np.sum(distances, axis=1) / (len(arr) - 1)
mean_distances

array([14.14213562, 11.62797818,  9.7423601 ,  8.48528137,  7.85674201,
        7.85674201,  8.48528137,  9.7423601 , 11.62797818, 14.14213562])

In [56]:
arr[mean_distances < 10]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

# PyTorch

### 4. SImple derivative (1 point).

Given some value of `x0`, calculate a derivative of sigmoid function at that point. Input is a single floating point value. Output must also be a single floating point value (not a tensor!) equal to derivative of $\sigma(x)$ at `x0`.

Do not use the exact formula for the derivative, but use PyTorch `.backward()`.

In [ ]:
def d_sigmoid(x0):
    """Derivative of sigmoid."""
    pass

In [ ]:
PROBLEM_ID = 4

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, d_sigmoid)

# Pandas

### 5. Ratio of males travelling alone per class (1 point).

Given the Titanic dataset, calculate ratio of males travelling alove (`SibSp==0` and `Parch==0`) per class. In other words, calculate number of males travelling alone in each class, divided by number of passengers in that class.

Input is indexed with `PassengerId` and is a concatenation of train and test sets. Output must be a series, indexed by class, containing the requested ratios.

In [75]:
#import datasets and combine them
test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv")
df = pd.concat([train, test], sort=False)


df_alone_males = df.loc[(df.SibSp == 0) & (df.Parch == 0) & (df.Sex == 'male')]
return df_alone_males.groupby('Pclass').size() / df.groupby('Pclass').size()

Pclass
1    0.334365
2    0.418773
3    0.524683
dtype: float64

In [74]:
import pandas as pd

# Read the Titanic datasets
test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv")

# Combine train and test sets
df = pd.concat([train, test], sort=False)

# Filter for males traveling alone (SibSp == 0, Parch == 0, and Sex == 'male')
df_males_alone = df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'male')]

# Compute number of males traveling alone in each class
count_males_alone = df_males_alone.groupby('Pclass').size()

# Compute total number of passengers in each class
count_per_class = df.groupby('Pclass').size()

# Calculate the ratio
ratio = count_males_alone / count_per_class

# ratio is a series indexed by class, containing the requested ratios
ratio


Pclass
1    0.334365
2    0.418773
3    0.524683
dtype: float64

In [59]:
PROBLEM_ID = 5

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, lone_males)

### 6. Worst days on UK roads in 2005 (2 points).

Calculate Top-5 days with the largest number of severe accidents (`Accident_Severity < 3`).

Input is a **dataframe**, containing all the accidents in 2005 and the following columns: `date_time` (constructed in the same way, as in optional time series notebook) and `Accident_Severity`. Index is a default integer index. Result must be a list (or tuple) of dates (as a `pd.Timestamp`) with 5 elements.

In [121]:
import pandas as pd

df = pd.read_csv('accidents_2005.csv')
df['date_time'] = pd.to_datetime(df['date_time'])
df['date'] = df['date_time'].dt.date
top_5_days = df[df['Accident_Severity'] < 3].groupby('date').size().nlargest(5)

print([pd.Timestamp(d) for d in top_5_days.index])


[Timestamp('2005-05-14 00:00:00'), Timestamp('2005-06-18 00:00:00'), Timestamp('2005-09-16 00:00:00'), Timestamp('2005-11-04 00:00:00'), Timestamp('2005-12-23 00:00:00')]


In [ ]:
PROBLEM_ID = 6

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, worst_days)

In [ ]:
if TEST:
    print(f"{STUDENT}: {int(100 * total_grade / MAX_POINTS)}")